services:
  aonsoku:
    image: ghcr.io/gatzenga/aonsoku:latest
    container_name: aonsoku
    restart: unless-stopped
    environment:
      - PUID=1035
      - PGID=100
      - NAVIDROME_URL=http://172.168.22.10:4533
      - LANGUAGE=de
      - LYRICS_SERVER=https://lrclib.vkugler.ch
      - THEME=
      - SIDEBAR_ARTISTS=true
      - SIDEBAR_SONGS=true
      - SIDEBAR_ALBUMS=true
      - SIDEBAR_GENRES=true
      - SIDEBAR_RADIOS=true
      - FEATURE_FAVORITES=true
      - FEATURE_PLAYLISTS=true
      - CACHE_IMAGES=true
      - CACHE_LYRICS=true
    volumes:
      - /volume2/docker/aonsoku/cache:/cache
    ports:
      - "127.0.0.1:9180:8080"
    networks:
      navidrome:
        ipv4_address: 172.168.22.80

networks:
  navidrome:
    external: true
